repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types_or: [c, c++]
        files: '^(firmware/.*/user/|resources/Drivers/SG_Drivers/).*.(c|cpp|h|hpp)$'
        args: [--style=file]
