name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pin to the same major you use locally (rev v17.0.6 in pre-commit)
      - name: Install clang-format 17
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-17
          sudo ln -sf /usr/bin/clang-format-17 /usr/local/bin/clang-format
          clang-format --version

      - name: Run clang-format (verify no diffs)
        shell: bash
        run: |
          set -eo pipefail
          echo "Checking formatting (user/ + SG_Drivers only)..."

          # Collect only our sources (avoid HAL/CMSIS/Middlewares/etc)
          mapfile -d '' -t FILES < <(
            find \
              firmware -path 'firmware/*/user/*' -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) -print0
          )
          mapfile -d '' -t SG_FILES < <(
            find \
              resources/Drivers/SG_Drivers -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) -print0
          )
          FILES=("${FILES[@]}" "${SG_FILES[@]}")

          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No source files found to check."
            exit 0
          fi

          # Dry-run check; fail if formatting would change
          printf '%s\0' "${FILES[@]}" | xargs -0 -n 100 clang-format -style=file -n --Werror
  build:
    name: Build (Debug & Release)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM GCC & build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            cmake \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi

      - name: Configure (${{ matrix.preset }})
        run: cmake --preset ${{ matrix.preset }}

      - name: Build (${{ matrix.preset }})
        run: cmake --build --preset ${{ matrix.preset }} --target all

      - name: Collect firmware artifacts
        if: always()
        run: |
          mkdir -p artifacts/${{ matrix.preset }}
          find build/${{ matrix.preset }} \
            -maxdepth 4 \
            -type f \( -name '*.elf' -o -name '*.bin' -o -name '*.hex' -o -name '*.map' \) \
            -exec cp -v {} artifacts/${{ matrix.preset }}/ \; || true

      - name: Upload artifacts (${{ matrix.preset }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.preset }}
          path: artifacts/${{ matrix.preset }}
          if-no-files-found: warn
